POS Terminal Empty Check
Adyen/adyen-salesforce-commerce-cloud pull request #368
Opened 2020-09-19 07:13 UTC by theShortJ

Added empty JSON check for the POS terminal variable. It was causing the page to break.

## Summary

## Tested scenarios

**Fixed issue**:

2020-10-12 07:17 UTC, maassenbas commented
Hi @theShortJ , 

Thanks for you PR. 
We will verify it and add it to the code.

Kind regards,
Bas Maassen
Adyen

2020-10-14 09:46 UTC, msilvagarcia requested changes
Hey there,

I believe there are better ways of checking for an empty object than using `JSON.stringify`.

Other than that, seems like a good idea.

Kind regards,
Marcos
Adyen

2020-10-23 09:09 UTC, OleksiiKravchenkoOSF commented
Hello, guys @maassenbas @msilvagarcia 

We also faced this issue and I think a more elegant solution will be if we just define the variable that going to be parsed as a string.
line 519 - `var connectedTerminals = "{}";` or `var connectedTerminals = JSON.stringify({})`

Thank you

2020-10-23 09:34 UTC, maassenbas commented
Hi @OleksiiKravchenkoOSF and @theShortJ , 

Basically, we already set the connectedTerminals to "{}" in the getConnectedTerminals() here: 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/getPaymentMethod/utils.js#L29 

I assume that will solve this issue.
Could you confirm that? 

Thanks,
Bas Maassen
Adyen

2020-10-23 09:56 UTC, OleksiiKravchenkoOSF commented
> Hi @OleksiiKravchenkoOSF and @theShortJ ,
> 
> Basically, we already set the connectedTerminals to "{}" in the getConnectedTerminals() here:
> https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/getPaymentMethod/utils.js#L29
> 
> I assume that will solve this issue.
> Could you confirm that?
> 
> Thanks,
> Bas Maassen
> Adyen

@maassenbas Yes, this issue won't happen with the latest version of Adyen. 
In my case, I have prev version like `Adyen Payment 20.1.0` where this issue occurs and probably we need to migrate to the latest one somewhen in the future. 

Thank you for your support!

2020-10-23 10:20 UTC, maassenbas commented
@OleksiiKravchenkoOSF Thanks for confirming! 
I will make sure this is covered in the upcoming release and close this PR then.

2020-10-28 10:13 UTC, closed without merging