Pw 5413/hide giftcard component
Adyen/adyen-salesforce-commerce-cloud pull request #545
Opened 2021-09-09 06:17 UTC by wboereboom

## Summary
gift card components should be hidden, brand should be included in the payments request, and HPP-Fallback should be used to resolve these requests

2021-09-10 08:22 UTC, zaiddreakh requested changes

2021-09-10 08:22 UTC, zaiddreakh commented on src/cartridges/int_adyen_controllers/cartridge/js/pages/checkout/adyen-checkout.js
> +        ...(brand ? { brand } : undefined),
for SG we can't use es6 unfortunately

2021-09-10 13:39 UTC, zaiddreakh submitted a review, later dismissed

2021-09-10 13:39 UTC, zaiddreakh commented on src/cartridges/int_adyen_controllers/cartridge/js/pages/checkout/adyen-checkout.js
> +  const fallback = {
var instead of const
Otherwise looks good!

2021-09-14 09:25 UTC, zaiddreakh approved these changes

2021-09-14 09:36 UTC, maassenbas approved these changes

2021-09-14 09:54 UTC, merged