PW-5783 Adyen Giving empty configs bug
Adyen/adyen-salesforce-commerce-cloud pull request #598
Opened 2021-12-02 12:32 UTC by zaiddreakh

## Summary

When AG is enabled, but not configured, it will give an error on confirmation page
This PR is for both SFRA and SG

## Tested scenarios

**Fixed issue**:

2021-12-02 12:36 UTC, wboereboom submitted a review, later dismissed

2021-12-03 13:57 UTC, maassenbas commented on src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js
> +    var givingConfigs = {
Should we use `let` here?

2021-12-03 15:51 UTC, wboereboom requested changes

2021-12-03 15:51 UTC, wboereboom commented on src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js
> +    for (let config in givingConfigs) {
you can use const here

2021-12-03 15:51 UTC, wboereboom commented on src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js
> +    for (let config in givingConfigs) {
```suggestion
    for (const config in givingConfigs) {
```

2021-12-03 15:59 UTC, wboereboom submitted a review, later dismissed

2021-12-03 16:07 UTC, wboereboom approved these changes

2021-12-14 06:52 UTC, wboereboom approved these changes

2021-12-16 16:55 UTC, maassenbas approved these changes

2021-12-17 11:42 UTC, closed without merging