Pw 7364/fix lgtm alerts
Adyen/adyen-salesforce-commerce-cloud pull request #717
Opened 2022-10-28 11:32 UTC by amihajlovski

2022-10-31 15:30 UTC, wboereboom requested changes
@zaiddreakh We need to investigate if these core code change fixes break the code

2022-10-31 15:30 UTC, wboereboom commented on src/cartridges/adyen_controllers_changes/app_storefront_controllers_changes/cartridge/controllers/PaymentInstruments.js
> -/**
I wonder if this is safe to delete. This extends core code functionality.

2022-10-31 15:30 UTC, wboereboom commented on src/cartridges/adyen_controllers_changes/app_storefront_controllers_changes/cartridge/controllers/COSummary.js
> -// ### Custom Adyen cartridge start ###
I wonder if this is safe to delete. This extends core code functionality.

2022-11-02 10:35 UTC, zaiddreakh approved these changes

2022-11-02 10:38 UTC, maassenbas approved these changes

2022-11-07 16:17 UTC, zenit2001 approved these changes

2022-11-08 07:35 UTC, zaiddreakh approved these changes

2022-11-08 07:44 UTC, merged